exclude = [
    ".git",
    "__pycache__",
    "ecoscope/contrib/foliumap.py",
    "ecoscope/io/earthranger.py",
]
ignore = [
    "B006",
    "B007",
    "B008",
    "B009",
    "B011",
    "B012",
    "B020",
    "B027",
    "B904",
    "B905",
    "C901",
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    "D200",
    "D201",
    "D202",
    "D205",
    "D209",
    "D212",
    "D301",
    "D400",
    "D401",
    "D404",
    "D407",
    "D415",
    "D417",
    "E501",
    "EXE002",
    "I001",
    "PIE794",
    "PIE796",
    "PIE804",
    "PIE810",
    "PT001",
    "PT004",
    "PT006",
    "PT007",
    "PT012",
    "PT015",
    "PT017",
    "PT018",
    "PT022",
    "PT023",
    "S101",
    "S102",
    "S104",
    "S105",
    "S110",
    "S311",
    "S324",
    "S608",
    "T201",
    "D213",
    "D203",
]
line-length = 120
select = ["B", "C", "D", "E", "EXE", "F", "I", "PIE", "PT", "S", "T", "W"]
